<?php

declare(strict_types=1);

namespace Freema\N8nBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('n8n');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('clients')
                    ->useAttributeAsKey('name')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('base_url')
                                ->isRequired()
                                ->cannotBeEmpty()
                            ->end()
                            ->scalarNode('client_id')
                                ->isRequired()
                                ->cannotBeEmpty()
                            ->end()
                            ->scalarNode('auth_token')
                                ->defaultNull()
                            ->end()
                            ->integerNode('timeout_seconds')
                                ->defaultValue(30)
                                ->min(1)
                            ->end()
                            ->integerNode('retry_attempts')
                                ->defaultValue(3)
                                ->min(0)
                            ->end()
                            ->integerNode('retry_delay_ms')
                                ->defaultValue(1000)
                                ->min(0)
                            ->end()
                            ->booleanNode('enable_circuit_breaker')
                                ->defaultTrue()
                            ->end()
                            ->integerNode('circuit_breaker_threshold')
                                ->defaultValue(5)
                                ->min(1)
                            ->end()
                            ->integerNode('circuit_breaker_timeout_seconds')
                                ->defaultValue(60)
                                ->min(1)
                            ->end()
                            ->booleanNode('dry_run')
                                ->defaultFalse()
                            ->end()
                            ->arrayNode('default_headers')
                                ->useAttributeAsKey('name')
                                ->normalizeKeys(false)
                                ->prototype('scalar')->end()
                            ->end()
                            ->scalarNode('proxy')
                                ->defaultNull()
                                ->info('HTTP proxy URL (e.g., http://proxy.example.com:3128)')
                            ->end()
                            ->booleanNode('use_test_webhook')
                                ->defaultFalse()
                                ->info('Use n8n test webhook URL (/webhook-test/) instead of production (/webhook/). Useful for unpublished workflows during development.')
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('callback')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('route_name')
                            ->defaultValue('n8n_callback')
                        ->end()
                        ->scalarNode('route_path')
                            ->defaultValue('/n8n/callback')
                            ->setDeprecated('freema/n8n-bundle', '2.1', 'The "%node%" option at "%path%" is not used. Define the callback route in your routing configuration instead (see the README).')
                        ->end()
                        ->scalarNode('secret')
                            ->defaultNull()
                            ->info('Key for signing callback URLs. Defaults to "kernel.secret" (framework.secret).')
                        ->end()
                        ->booleanNode('require_signature')
                            ->defaultTrue()
                            ->info('Reject callbacks without a valid signature. Turn off only while migrating n8n workflows that post to a fixed URL.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('tracking')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('cleanup_interval_seconds')
                            ->defaultValue(3600)
                            ->min(60)
                        ->end()
                        ->integerNode('max_request_age_seconds')
                            ->defaultValue(86400)
                            ->min(300)
                            ->info('How long a callback is accepted after the request was sent.')
                        ->end()
                        ->scalarNode('cache_pool')
                            ->defaultValue('cache.app')
                            ->info('Cache pool that keeps callback requests between processes. Must be shared by every process that receives callbacks. Null keeps them in process memory only.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('debug')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultNull()
                            ->info('Enable debug mode. When null, auto-detects based on kernel.debug parameter')
                        ->end()
                        ->booleanNode('log_requests')
                            ->defaultTrue()
                            ->info('Log N8n requests to configured logger')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
