services:
  php:
    container_name: n8n-bundle-php
    image: php:8.2-cli
    ports:
      - "8080:8080"
    volumes:
      - ./:/code:cached
      - ~/.composer/cache:/root/.composer/cache:cached
    working_dir: /code
    tty: true
    stdin_open: true
    command: >
      bash -c "apt-get update && apt-get install -y git unzip curl && 
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && 
      tail -f /dev/null"